FROM owncloud/base:20.04-arm64v8@sha256:6542c79cbff0852e0eeb29b49ff27ef967b80dc8e76f5d460c0e097f434d50ed

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.title="ownCloud Server" \
  org.opencontainers.image.description="ownCloud - Secure Collaboration Platform" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/server" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/server" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/server"

VOLUME ["/mnt/data"]
EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/owncloud", "server"]

ADD owncloud.tar.bz2 /var/www/

ADD overlay /
WORKDIR /var/www/owncloud

RUN find /var/www/owncloud \( \! -user www-data -o \! -group root \) -print0 | xargs -r -0 chown www-data:root && \
  chmod g+w /var/www/owncloud /var/www/owncloud/.htaccess
