FROM owncloud/base:20.04-amd64@sha256:0bba7e8633b999cb35fd8b3ced7540636f6d7979f8587664065f32c580c71ee1

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.title="ownCloud Server" \
  org.opencontainers.image.description="ownCloud - Secure Collaboration Platform" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/server" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/server" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/server"

ADD owncloud.tar.bz2 /var/www/

ADD overlay /
WORKDIR /var/www/owncloud

RUN find /var/www/owncloud \( \! -user www-data -o \! -group root \) -print0 | xargs -r -0 chown www-data:root && \
  chmod g+w /var/www/owncloud /var/www/owncloud/.htaccess

VOLUME ["/mnt/data"]
EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/owncloud", "server"]
