FROM owncloud/base:22.04@sha256:910a6e1f12b9e3b908d2a0221b92cd44b817e29fcbd2902c8271edf0373ead8c

ARG TARBALL_URL

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.title="ownCloud Server" \
  org.opencontainers.image.description="ownCloud - Secure Collaboration Platform" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/server" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/server" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/server"

ADD --unpack ${TARBALL_URL} /var/www/

ADD overlay /
WORKDIR /var/www/owncloud

RUN find /var/www/owncloud \( \! -user www-data -o \! -group root \) -print0 | xargs -r -0 chown www-data:root && \
  chmod g+w /var/www/owncloud /var/www/owncloud/.htaccess

VOLUME ["/mnt/data"]
EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/owncloud", "server"]
