workspace:
  base: /drone
  path: src/github.com/owncloud-docker/server

branches:
  - master
  - 9.1.x
  - 9.0.x

clone:
  git:
    image: plugins/git:1
    pull: true

pipeline:
  tarball:
    image: plugins/download:latest
    pull: true
    secrets: [ download_username, download_password ]
    source: https://download.owncloud.org/community/owncloud-${CORE_VERSION}.tar.bz2
    sha256: ${CORE_CHECKSUM}

  ldap:
    image: plugins/download:latest
    pull: true
    source: https://github.com/owncloud/user_ldap/releases/download/${LDAP_VERSION}/user_ldap.tar.gz
    sha256: ${LDAP_CHECKSUM}

  wait:
    image: owncloud/ubuntu:latest
    pull: true
    commands:
      - wait-for-it -t 600 docker:2375

  build:
    image: toolhippie/docker:latest
    pull: true
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker build -t owncloud/server:latest .

  server:
    image: toolhippie/docker:latest
    pull: true
    detach: true
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker run -p 8000:80 owncloud/server:latest

  test:
    image: owncloud/ubuntu:latest
    pull: true
    commands:
      - wait-for-it -t 600 docker:8000
      - curl -sSf http://docker:8000/status.php

  publish:
    image: toolhippie/docker:latest
    pull: true
    secrets: [ docker_username, docker_password ]
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - |
        for IMAGE in ${IMAGE_TAGS}; do
          docker tag owncloud/server:latest owncloud/server:$IMAGE
          docker push owncloud/server:$IMAGE
        done
    when:
      event: [ push ]

  microbadger:
    image: plugins/webhook:1
    pull: true
    secrets: [ webhook_urls ]
    when:
      local: false
      event: [ push ]

  slack:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: docker
    template: >
      *{{build.status}}* <{{build.link}}|{{repo.owner}}/{{repo.name}}#{{truncate build.commit 8}}> @ ${CORE_VERSION}
    when:
      local: false
      event: [ push ]
      status: [ changed, failure ]

services:
  docker:
    image: docker:18.04-dind

matrix:
  include:
    - CORE_VERSION: 10.0.8
      CORE_CHECKSUM: 9eef77a171cf69fc89b0628b083b4b1dd15eec375599c7eb5ac0b6d37ab6f903
      LDAP_VERSION: v0.11.0
      LDAP_CHECKSUM: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      IMAGE_TAGS: 10.0.8 10.0 latest

    - CORE_VERSION: 10.0.7
      CORE_CHECKSUM: 7c822aa163182391ae3213a5465151d7cc7dd0990666315da0d8e118269d0fb0
      LDAP_VERSION: v0.10.0
      LDAP_CHECKSUM: a779b3d435c170d74365853b66962e8020712c7775a0a2399519eea4bf93585d
      IMAGE_TAGS: 10.0.7

    - CORE_VERSION: 10.0.6
      CORE_CHECKSUM: de5153f059a7cecf5f191de053ff3ab4dea21ffba2b3ef207309e58443a6e6c4
      LDAP_VERSION: v0.10.0
      LDAP_CHECKSUM: a779b3d435c170d74365853b66962e8020712c7775a0a2399519eea4bf93585d
      IMAGE_TAGS: 10.0.6

    - CORE_VERSION: 10.0.4
      CORE_CHECKSUM: e150f0b413376b0da5225dcdc372938c49ca702cab3759e59db2d3ab79b2bcb8
      LDAP_VERSION: v0.10.0
      LDAP_CHECKSUM: a779b3d435c170d74365853b66962e8020712c7775a0a2399519eea4bf93585d
      IMAGE_TAGS: 10.0.4

    - CORE_VERSION: 10.0.3
      CORE_CHECKSUM: f489e072090d51e47b390109297d7aaee56dd39c42d8d149fb0b7d002c3ac38d
      LDAP_VERSION: v0.10.0
      LDAP_CHECKSUM: a779b3d435c170d74365853b66962e8020712c7775a0a2399519eea4bf93585d
      IMAGE_TAGS: 10.0.3

    - CORE_VERSION: 10.0.2
      CORE_CHECKSUM: 3645214d6b9527dc218b4cdcbbf1d01809aaba14435d644b545bee0274c88fd0
      LDAP_VERSION: v0.10.0
      LDAP_CHECKSUM: a779b3d435c170d74365853b66962e8020712c7775a0a2399519eea4bf93585d
      IMAGE_TAGS: 10.0.2

    - CORE_VERSION: 10.0.1
      CORE_CHECKSUM: ae69444e0eabd085682fd8abc8f4addfcaa5213b5d40819f83dd8aa5f8dad896
      LDAP_VERSION: v0.10.0
      LDAP_CHECKSUM: a779b3d435c170d74365853b66962e8020712c7775a0a2399519eea4bf93585d
      IMAGE_TAGS: 10.0.1

    # - CORE_VERSION: 10.0.0
    #   CORE_CHECKSUM: 488fc136a8000b42c447e224e69f16f5c31a231eea3038614fdea5e0c2218457
    #   LDAP_VERSION: v10.0.0RC2
    #   LDAP_CHECKSUM: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    #   IMAGE_TAGS: 10.0.0
