#!/bin/bash
source .env

docker build \
  --build-arg VERSION=${VERSION} \
  --build-arg TARBALL=${TARBALL} \
  --build-arg RICHDOCUMENTS=${RICHDOCUMENTS} \
  --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --build-arg VCS_REF=$(git rev-parse --short HEAD) \
  -t ${IMAGE_NAME} .
